// auto generated by go tool dist

package runtime

const defaultGoroot = `/private/var/folders/++/++2REE++6+0++4RjPqRgNE+-5I2/-Tmp-/appengine/google_appengine/goroot`
const theVersion = `go1.0.2 (appengine-1.7.1)`
